openapi: 3.1.0
info:
  title: IGEL Knowledge Base Vector Store Connector
  version: 2.2.1
  description: |
    Search the IGEL Knowledge Base OpenAI Vector Store.
    Retrieve relevant knowledge, enablement resources, product details, and case studies.

servers:
  - url: https://api.openai.com/v1

paths:
  /vector_stores/vs_67b4fd37caec8191baf3cb6bb625f6a0/search:
    post:
      summary: Semantic search on IGEL Knowledge Base Vector Store
      operationId: searchIgelVectorStore
      description: >
        Performs a semantic search in the IGEL Knowledge Base OpenAI Vector Store.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: Natural-language search string.
                  example: "Universal Management Suite disaster recovery playbook"
                filter:
                  type: object
                  description: (Optional) Metadata filter for search results.
                  additionalProperties: true
      responses:
        "200":
          description: Successful vector store search
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        document_id:
                          type: string
                          description: The ID of the matched document.
                        text:
                          type: string
                          description: The matched passage or chunk.
                        metadata:
                          type: object
                          description: Metadata for the matched chunk.
                          additionalProperties: true
        "400":
          description: Bad request — missing required fields.
        "403":
          description: Forbidden — authentication or access denied.
        "404":
          description: Not found — vector store not found.
        "500":
          description: Internal server error.
